### ISSUE TITLE
SwipeableState在1.6已弃用

### ISSUE THREAD

**Issue by qiushui95** [KevinnZou/compose-swipeBox#1]
麻烦在1.6稳定的时候修改一下api。谢谢

**Comment by qiushui95** [comment]
https://developer.android.com/jetpack/compose/touch-input/pointer-input/migrate-swipeable

**Comment by KevinnZou** [comment]
@qiushui95 Thanks for your suggestion! I will do it when it is stable.

**Comment by qiushui95** [comment]
1.6.0 is stable

**Comment by KevinnZou** [comment]
@qiushui95 Thanks for your remind! I will start working on it next week.

**Comment by KevinnZou** [comment]
@qiushui95 I have submitted a pull request for it. I would appreciate it if you could review it.

**Comment by NavjotSinghSeraphic** [comment]
how  we  can add text with icon

**Comment by KevinnZou** [comment]
> how we can add text with icon

@NavjotSinghSeraphic Have you tried using a column or row to warp them?

**Comment by NavjotSinghSeraphic** [comment]
@KevinnZou  can you give me a example code
